repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        types:
          - python
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --allow-past-years
          - --use-current-year

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39f54b73c72a16ee873859353d1ef40552a22e4d
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.0.1
    hooks:
      - id: cspell
        pass_filenames: false
        args:
          - --unique
          - --no-progress
          - --no-summary
          - --show-suggestions
          - --no-cache
          - --dot
          - --gitignore
          - --validate-directives
          - "."

  - repo: local
    hooks:
      - id: pyright
        language: system
        name: pyright
        entry: uv run --all-extras pyright
        args:
          - --threads
          - "4"
          - .
        pass_filenames: false
