version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - tests/markdown/spec/
useGitignore: true
dictionaryDefinitions: []
dictionaries:
  - companies
  - misc
  - softwareTerms
  - typescript
  - node
  - python
  - html
  - css
  - bash
  - filetypes
  - npm
  - docker
  - k8s
  - python-common
  - sql
words:
  - addopts
  - clazz
  - injex
  - iyanging
  - typeshed
ignoreWords: []
import: []
